name: PHP Embed
version: 1.13.0
icon:
  name: php
  set: "fontawesome|brands"
description: PHP Embed plugin allows you to embed php code into your page.
author:
  name: Sergey Romanenko
  email: sergey.romanenko@flextype.org
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/php-embed
bugs: https://github.com/flextype-plugins/php-embed/issues
license: MIT

dependencies:
  flextype: 0.9.16
