name: PHP Embed
version: 1.8.0
icon: fab fa-php
description: PHP Embed plugin allows you to embed php code into your page.
author:
  name: Sergey Romanenko
  email: awilum@yandex.ru
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/php-embed
bugs: https://github.com/flextype-plugins/php-embed/issues
license: MIT

dependencies:
  flextype: 0.9.12
